name: Shellcheck
run-name: ${{ github.actor }} PR checker
on: 
    push:
        paths:
            - '**.sh'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: perts-'${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  run-shellcheck:
    runs-on: client
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y shellcheck
      - run: shellcheck --version
      - run: shellcheck scripts/*.sh
